---
- name: Create stacks/base directory
  ansible.builtin.file:
    path: "{{ base_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Create Dockerfile from template
  ansible.builtin.template:
    src: Dockerfile.j2
    dest: "{{ base_dir }}/Dockerfile"
    mode: '0644'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Create compose.yml from template
  ansible.builtin.template:
    src: compose.yml.j2
    dest: "{{ base_dir }}/compose.yml"
    mode: '0644'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Copy .config directory to build context
  ansible.builtin.copy:
    src: .config/
    dest: "{{ base_dir }}/.config/"
    mode: '0644'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Create base directory on host
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/base"
    state: directory
    mode: '0755'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Create claude settings directory on host
  ansible.builtin.file:
    path: "/home/{{ admin_user }}/.claude"
    state: directory
    mode: '0755'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Copy .config directory to host base directory
  ansible.builtin.copy:
    src: .config/
    dest: "/home/{{ admin_user }}/base/.config/"
    mode: '0644'
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']

- name: Build and start base container
  community.docker.docker_compose_v2:
    project_src: "{{ base_dir }}"
    build: always
    state: present
  become: true
  become_user: "{{ admin_user }}"
  tags: ['base-container']
