---
- name: Get system memory information
  ansible.builtin.setup:
    filter: ansible_memtotal_mb
  tags: ['swap-setup']

- name: Calculate optimal swap size
  ansible.builtin.set_fact:
    swap_size_mb: "{{ [ansible_memtotal_mb, 2048] | min }}"
  tags: ['swap-setup']

- name: Check if swap file already exists
  ansible.builtin.stat:
    path: /swapfile
  register: swap_file_check
  tags: ['swap-setup']

- name: Create swap file
  ansible.builtin.command:
    cmd: "dd if=/dev/zero of=/swapfile bs=1M count={{ swap_size_mb }}"
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  tags: ['swap-setup']

- name: Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    mode: '0600'
  when: not swap_file_check.stat.exists
  tags: ['swap-setup']

- name: Make swap file
  ansible.builtin.command:
    cmd: mkswap /swapfile
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  tags: ['swap-setup']

- name: Enable swap file
  ansible.builtin.command:
    cmd: swapon /swapfile
  when: not swap_file_check.stat.exists
  changed_when: not swap_file_check.stat.exists
  tags: ['swap-setup']

- name: Add swap to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "/swapfile none swap sw 0 0"
    state: present
  tags: ['swap-setup']

- name: Set optimal swappiness value
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness | default(20) }}"
    state: present
    reload: true
  tags: ['swap-setup']

- name: Set VFS cache pressure
  ansible.posix.sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_vfs_cache_pressure | default(50) }}"
    state: present
    reload: true
  tags: ['swap-setup']
