---
- name: Install Docker using geerlingguy.docker role
  ansible.builtin.include_role:
    name: geerlingguy.docker
  tags: ['docker-setup']

- name: Add admin user to docker group
  ansible.builtin.user:
    name: "{{ admin_user }}"
    groups: docker
    append: true
  tags: ['docker-setup']
