---
- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: "{{ caddy_gpg_key_url }}"
    state: present
  become: true
  retries: 3
  delay: 10

- name: Add Caddy repository
  ansible.builtin.apt_repository:
    repo: "{{ caddy_repository }}"
    state: present
  become: true

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  retries: 3
  delay: 5

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  become: true

- name: Verify Caddy installation
  ansible.builtin.command: caddy version
  register: caddy_version_check
  changed_when: false
  failed_when: caddy_version_check.rc != 0

- name: Create caddy directory
  ansible.builtin.file:
    path: "{{ caddy_user_home }}/caddy"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: '0755'
  become: true

- name: Create logs directory
  ansible.builtin.file:
    path: "{{ caddy_user_home }}/caddy/logs"
    state: directory
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: '0755'
  become: true

- name: Create Caddyfile from template
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ caddy_user_home }}/caddy/Caddyfile"
    owner: "{{ caddy_user }}"
    group: "{{ caddy_user }}"
    mode: '0644'
  become: true
  notify: Restart caddy

- name: Configure Caddy service
  ansible.builtin.template:
    src: caddy.service.j2
    dest: /etc/systemd/system/caddy.service
    mode: '0644'
  become: true
  notify:
    - Reload systemd
    - Restart caddy

- name: Enable and start Caddy service
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
    daemon_reload: true
  become: true

- name: Wait for Caddy to be ready
  ansible.builtin.wait_for:
    port: 80
    host: "{{ ansible_default_ipv4.address }}"
    timeout: 30
  when: ansible_default_ipv4.address is defined

- name: Verify Caddy service is running
  ansible.builtin.systemd:
    name: caddy
  register: caddy_service_status
  failed_when: caddy_service_status.status.ActiveState != "active"
