---
groups:
  - name: system_monitoring
    rules:
      - alert: HighCPUUsage
        expr: >-
          100 - (avg by(instance)
          (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: >-
            CPU usage is above 80% for more than 5 minutes
            (current value: {{ $value }}%)

      - alert: HighMemoryUsage
        expr: >-
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))
          * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: >-
            Memory usage is above 90% for more than 5 minutes
            (current value: {{ $value }}%)

      - alert: LowDiskSpace
        expr: >-
          (node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} /
          node_filesystem_size_bytes < 0.10 and on (instance, device, mountpoint)
          node_filesystem_readonly == 0)
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: >-
            Disk space is critically low (< 10% available) on mountpoint
            {{ $labels.mountpoint }}

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: >-
            {{ $labels.job }} on {{ $labels.instance }} has been down
            for more than 1 minute

      - alert: HighLoadAverage
        expr: node_load1 > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High load average on {{ $labels.instance }}"
          description: "Load average is {{ $value }} (threshold: 2.0)"
