---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  tags: ['system-update']

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    autoclean: true
  register: apt_upgrade_result
  tags: ['system-update']

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags: ['system-update']

- name: Set reboot required fact
  ansible.builtin.set_fact:
    reboot_required: true
  when: reboot_required_file.stat.exists
  tags: ['system-update']
